version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install google-api-python-client pandas snowflake-connector-python
  build:
    commands:
      - echo "Running YouTube data fetching script..."
      - python ingestion/youtube_data_pipeline.py
artifacts:
  files:
    - '**/*'  # Optional: Keep if you want to include any log files or outputs
  discard-paths: yes
